Repository woowacourse/prolog, pull requests merged in 2023-09, with the labels that each got.

#1512 js > ts 마이그레이션
  frontend/src/components/CreatableSelectBox/CreatableSelectBox.tsx
  frontend/src/components/SearchBar/SearchBar.styles.tsx
  frontend/src/components/SearchBar/SearchBar.tsx
Labels: FE

#1518 react router dom 유틸 훅 추가
  frontend/src/hooks/useValidParams.ts
  frontend/src/hooks/useValidQueryString.ts
  frontend/src/utils/arrayMutation.ts
Labels: FE

#1520 Refactor/1517 migration
  frontend/src/components/Tag/Tag.js
  frontend/src/components/Tag/Tag.styles.ts
  frontend/src/components/Tag/Tag.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/useSnackBar.tsx
  frontend/src/redux/reducers/index.ts
  frontend/src/redux/reducers/snackBarReducer.ts
  frontend/src/redux/store.ts
Labels: FE

#1510 전체 키워드 조회 시 학습 진도를 포함한다
  backend/src/documentation/java/wooteco/prolog/docu/KeywordDocumentation.java
  backend/src/main/java/wooteco/prolog/roadmap/application/RoadMapService.java
  backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordResponse.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/repository/EssayAnswerRepository.java
  backend/src/main/java/wooteco/prolog/roadmap/ui/RoadmapController.java
  backend/src/test/java/wooteco/prolog/roadmap/application/RoadMapServiceTest.java
  backend/src/test/java/wooteco/prolog/roadmap/repository/EssayAnswerRepositoryTest.java
Labels: BE, 로드맵

#1528 refactor : ts로 마이그레이션한다
  frontend/src/hooks/useFilterWithParams.ts
  frontend/src/hooks/useNotFound.ts
  frontend/src/pages/EssayAnswerPage/Content.tsx
  frontend/src/pages/LevellogPage/Content.tsx
  frontend/src/pages/LoginCallbackPage/index.tsx
  frontend/src/pages/ProfilePage/index.tsx
  frontend/src/pages/ProfilePage/styles.ts
  frontend/src/pages/ProfilePageAccount/index.tsx
  frontend/src/pages/ProfilePageScraps/styles.ts
  frontend/src/pages/ProfilePageStudylogs/styles.ts
  frontend/src/pages/index.ts
  frontend/src/redux/actions/snackBarAction.ts
  frontend/src/styles/markdown.styles.ts
Labels: FE

#1532 fix: 타입 검사 건너뛰는 코드 제거
  .github/workflows/front-dev.yml
Labels: FE

#1544 Feature/#1526 아티클 북마크 기능 추가
  backend/src/acceptanceTest/java/wooteco/prolog/steps/ArticleStepDefinitions.java
  backend/src/acceptanceTest/resources/wooteco/prolog/article.feature
  backend/src/documentation/adoc/article.adoc
  backend/src/documentation/java/wooteco/prolog/docu/ArticleDocumentation.java
  backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
  backend/src/main/java/wooteco/prolog/article/domain/Article.java
  backend/src/main/java/wooteco/prolog/article/domain/ArticleBookmark.java
  backend/src/main/java/wooteco/prolog/article/domain/ArticleBookmarks.java
  backend/src/main/java/wooteco/prolog/article/domain/repository/ArticleRepository.java
  backend/src/main/java/wooteco/prolog/article/ui/ArticleBookmarkRequest.java
  backend/src/main/java/wooteco/prolog/article/ui/ArticleController.java
  backend/src/main/resources/db/migration/prod/V6__create_table_article_bookmark.sql
  backend/src/test/java/wooteco/prolog/article/application/ArticleServiceTest.java
  backend/src/test/java/wooteco/prolog/article/domain/ArticleBookmarkTest.java
  backend/src/test/java/wooteco/prolog/article/domain/ArticleBookmarksTest.java
  backend/src/test/java/wooteco/prolog/article/domain/ArticleTest.java
Labels: BE, 아티클

#1543 KeywordResponse에서 추천 포스트 emptyList 반환 로직 제거
  backend/src/documentation/java/wooteco/prolog/docu/KeywordDocumentation.java
  backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordResponse.java
Labels: bug, BE, 로드맵

#1551 feat: 아티클 북마크&필터링 기능 추가
  frontend/src/apis/articles.ts
  frontend/src/components/Article/Article.style.tsx
  frontend/src/components/Article/Article.tsx
  frontend/src/components/Article/ArticleBookmarkFIlter.tsx
  frontend/src/components/Article/ArticleList.style.tsx
  frontend/src/components/Article/ArticleList.tsx
  frontend/src/components/Controls/SelectBox.tsx
  frontend/src/components/Reaction/Scrap.styles.ts
  frontend/src/components/Reaction/Scrap.tsx
  frontend/src/hooks/queries/article.ts
  frontend/src/mocks/db/articles-android.json
  frontend/src/mocks/db/articles-backend.json
  frontend/src/mocks/db/articles-frontend.json
  frontend/src/mocks/db/articles.json
  frontend/src/mocks/handlers/articles.ts
  frontend/src/models/Article.ts
  frontend/src/pages/ArticleListPage/index.tsx
Labels: FE, 아티클

#1549 refactor : 엔드포인트에서 사용하지 않는 session ID가 있으면, 없애고 새로운 엔드포인트 생성
  backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/repository/KeywordRepository.java
  backend/src/main/java/wooteco/prolog/roadmap/ui/KeywordController.java
  backend/src/main/java/wooteco/prolog/roadmap/ui/QuizController.java
  backend/src/test/java/wooteco/prolog/roadmap/repository/KeywordRepositoryTest.java
Labels: BE

#1558 Feat/#1552: 아티클 좋아요 기능 추가와 authorization null 삭제
  frontend/src/apis/articles.ts
  frontend/src/apis/index.ts
  frontend/src/components/Article/Article.style.tsx
  frontend/src/components/Article/Article.tsx
  frontend/src/components/Reaction/Like.tsx
  frontend/src/hooks/queries/article.ts
  frontend/src/mocks/db/articles-android.json
  frontend/src/mocks/db/articles-backend.json
  frontend/src/mocks/db/articles-frontend.json
  frontend/src/mocks/db/articles.json
  frontend/src/mocks/handlers/articles.ts
  frontend/src/models/Article.ts
Labels: FE, 아티클
