Repository woowacourse/prolog, pull requests merged in 2023-08, with the labels that each got.

#1475 feat: articles 에 imageUrl 추가
  backend/src/main/java/wooteco/prolog/article/domain/Article.java
  backend/src/main/java/wooteco/prolog/article/domain/ImageUrl.java
  backend/src/main/java/wooteco/prolog/article/ui/ArticleRequest.java
  backend/src/main/java/wooteco/prolog/common/exception/BadRequestCode.java
  backend/src/main/resources/db/migration/prod/V5__alter_table_article.sql
  backend/src/test/java/wooteco/prolog/article/application/ArticleServiceTest.java
  backend/src/test/java/wooteco/prolog/article/domain/ArticleTest.java
  backend/src/test/java/wooteco/prolog/article/domain/ImageUrlTest.java
Labels: BE, 아티클

#1476 Refactor/#1426 meta og 관련 기능 추가 및 아티클 로직 개선
  frontend/src/apis/articles.ts
  frontend/src/components/Article/Article.style.tsx
  frontend/src/components/Article/Article.tsx
  frontend/src/components/Article/ArticleList.style.tsx
  frontend/src/configs/bannerList.tsx
  frontend/src/hooks/Articles/useArticles.ts
  frontend/src/mocks/db/articles.json
  frontend/src/mocks/db/metaog.json
  frontend/src/mocks/handlers/articles.ts
  frontend/src/models/Article.ts
  frontend/src/pages/NewArticlePage/index.tsx
  frontend/src/pages/NewArticlePage/styles.ts
Labels: FE, 아티클

#1483 refactor/#1482 변경된 metaOg api 반영 및 타입 추가
  frontend/src/apis/articles.ts
  frontend/src/hooks/Articles/useArticles.ts
  frontend/src/mocks/handlers/articles.ts
  frontend/src/models/Article.ts
  frontend/src/pages/NewArticlePage/index.tsx
Labels: FE, 아티클

#1484 Refactor/#1426 아티클 meta og 기능 및 고도화 코드 article-develop 머지
  frontend/src/apis/articles.ts
  frontend/src/components/Article/Article.style.tsx
  frontend/src/components/Article/Article.tsx
  frontend/src/components/Article/ArticleList.style.tsx
  frontend/src/configs/bannerList.tsx
  frontend/src/hooks/Articles/useArticles.ts
  frontend/src/mocks/db/articles.json
  frontend/src/mocks/db/metaog.json
  frontend/src/mocks/handlers/articles.ts
  frontend/src/models/Article.ts
  frontend/src/pages/NewArticlePage/index.tsx
  frontend/src/pages/NewArticlePage/styles.ts
Labels: FE, 아티클

#1472 feat : 커리큘럼 ID로 키워드들 조회 API 구현
  backend/src/main/java/wooteco/prolog/roadmap/application/RoadMapService.java
  backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordsResponse.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/Keyword.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/repository/KeywordRepository.java
  backend/src/main/java/wooteco/prolog/roadmap/ui/RoadmapController.java
  backend/src/test/java/wooteco/prolog/roadmap/application/RoadMapServiceTest.java
  backend/src/test/java/wooteco/prolog/roadmap/repository/KeywordRepositoryTest.java
Labels: BE, 로드맵

#1485 아티클을 최신순으로 정렬한다.
  backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
  backend/src/main/java/wooteco/prolog/article/domain/repository/ArticleRepository.java
Labels: BE, 아티클

#1481 Feat/1480 아티클 테스트 코드 추가
  backend/src/acceptanceTest/java/wooteco/prolog/fixtures/ArticleFixture.java
  backend/src/acceptanceTest/java/wooteco/prolog/steps/ArticleStepDefinitions.java
  backend/src/acceptanceTest/resources/wooteco/prolog/article.feature
  backend/src/main/java/wooteco/prolog/article/application/OgTagParser.java
  backend/src/main/java/wooteco/prolog/article/ui/ArticleUrlRequest.java
  backend/src/main/resources/application.yml
  backend/src/test/java/wooteco/prolog/article/application/ArticleServiceTest.java
  backend/src/test/java/wooteco/prolog/article/application/OgTagParserTest.java
Labels: BE, 아티클

#1488 fix: meta-og api url 수정
  backend/src/acceptanceTest/java/wooteco/prolog/steps/ArticleStepDefinitions.java
  backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
  backend/src/main/java/wooteco/prolog/article/application/MetaOgService.java
  backend/src/main/java/wooteco/prolog/article/application/OgTagParser.java
  backend/src/main/java/wooteco/prolog/article/ui/ArticleController.java
  backend/src/main/java/wooteco/prolog/article/ui/MetaOgController.java
  backend/src/main/java/wooteco/prolog/common/exception/BadRequestCode.java
  backend/src/test/java/wooteco/prolog/article/application/ArticleServiceTest.java
  backend/src/test/java/wooteco/prolog/article/application/MetaOgServiceTest.java
Labels: BE

#1489 fix: meta og url 인자오류 수정
  frontend/src/apis/articles.ts
Labels: bug, 아티클

#1490 refactor: 아티클 추가 로직에 useMutation 적용
  frontend/src/constants/message.ts
  frontend/src/hooks/queries/article.ts
  frontend/src/pages/NewArticlePage/index.tsx
Labels: FE, 아티클

#1491 fix: useQuery 미적용 코드 적용
  frontend/src/components/Article/ArticleList.tsx
Labels: bug, 아티클

#1493 meta og 태그를 이용하여 아티클 기능 구현
  backend/build.gradle
  backend/src/acceptanceTest/java/wooteco/prolog/fixtures/ArticleFixture.java
  backend/src/acceptanceTest/java/wooteco/prolog/steps/ArticleStepDefinitions.java
  backend/src/acceptanceTest/resources/wooteco/prolog/article.feature
  backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
  backend/src/main/java/wooteco/prolog/article/application/MetaOgService.java
  backend/src/main/java/wooteco/prolog/article/application/OgTagParser.java
  backend/src/main/java/wooteco/prolog/article/domain/Article.java
  backend/src/main/java/wooteco/prolog/article/domain/ImageUrl.java
  backend/src/main/java/wooteco/prolog/article/domain/repository/ArticleRepository.java
  backend/src/main/java/wooteco/prolog/article/ui/ArticleController.java
  backend/src/main/java/wooteco/prolog/article/ui/ArticleRequest.java
  backend/src/main/java/wooteco/prolog/article/ui/ArticleResponse.java
  backend/src/main/java/wooteco/prolog/article/ui/ArticleUrlRequest.java
  backend/src/main/java/wooteco/prolog/article/ui/ArticleUrlResponse.java
  backend/src/main/java/wooteco/prolog/article/ui/MetaOgController.java
  backend/src/main/java/wooteco/prolog/common/exception/BadRequestCode.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/db/migration/prod/V5__alter_table_article.sql
  backend/src/test/java/wooteco/prolog/article/application/ArticleServiceTest.java
  backend/src/test/java/wooteco/prolog/article/application/MetaOgServiceTest.java
  backend/src/test/java/wooteco/prolog/article/domain/ArticleTest.java
  backend/src/test/java/wooteco/prolog/article/domain/ImageUrlTest.java
  frontend/src/apis/articles.ts
  frontend/src/components/Article/Article.style.tsx
  frontend/src/components/Article/Article.tsx
  frontend/src/components/Article/ArticleList.style.tsx
  frontend/src/components/Article/ArticleList.tsx
  frontend/src/configs/bannerList.tsx
  frontend/src/constants/message.ts
  frontend/src/hooks/Articles/useArticles.ts
  frontend/src/hooks/queries/article.ts
  frontend/src/mocks/db/articles.json
  frontend/src/mocks/db/metaog.json
  frontend/src/mocks/handlers/articles.ts
  frontend/src/models/Article.ts
  frontend/src/pages/NewArticlePage/index.tsx
  frontend/src/pages/NewArticlePage/styles.ts
Labels: 아티클

#1494 Hotfix: og 태그가 없는 경우 null 을 반환하여 생기는 NPE 해결을 위해 빈문자열 반환
  backend/src/main/java/wooteco/prolog/article/application/OgTagParser.java
Labels: bug, BE

#1496 Fix/#1495 Meta Og 기본값 기능 버그 해결
  frontend/src/mocks/handlers/articles.ts
  frontend/src/pages/NewArticlePage/index.tsx
Labels: bug, FE, 아티클

#1498 아티클 MetaOG 빈문자열 관련 서버오류 처리 및 클라이언트 기본값 바인딩 기능 오류 수정
  backend/src/main/java/wooteco/prolog/article/application/OgTagParser.java
  frontend/src/mocks/handlers/articles.ts
  frontend/src/pages/NewArticlePage/index.tsx
Labels: FE, BE, 아티클

#1499 아티클 MetaOG 빈문자열 관련 서버오류 처리 및 클라이언트 기본값 바인딩 기능 오류 수정
  backend/src/main/java/wooteco/prolog/article/application/OgTagParser.java
  frontend/src/mocks/handlers/articles.ts
  frontend/src/pages/NewArticlePage/index.tsx
Labels: FE, BE, 아티클

#1501 Fix/#1500 flyway 설정 false로 수정
  backend/src/main/resources/application.yml
Labels: BE

#1433 Feature/1360 로드맵 답변 목록 검색 기능 추가
  backend/src/main/java/wooteco/prolog/common/exception/BadRequestCode.java
  backend/src/main/java/wooteco/prolog/roadmap/application/EssayAnswerService.java
  backend/src/main/java/wooteco/prolog/roadmap/application/dto/EssayAnswerResponse.java
  backend/src/main/java/wooteco/prolog/roadmap/application/dto/EssayAnswerSearchRequest.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/repository/EssayAnswerRepository.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/repository/EssayAnswerSpecification.java
  backend/src/main/java/wooteco/prolog/roadmap/ui/EssayAnswerController.java
  backend/src/main/java/wooteco/prolog/session/application/SessionService.java
  backend/src/main/java/wooteco/prolog/studylog/application/dto/EssayAnswersResponse.java
  backend/src/test/java/wooteco/prolog/roadmap/application/EssayAnswerSearchTest.java
  backend/src/test/java/wooteco/prolog/session/application/SessionServiceTest.java
  backend/src/test/java/wooteco/prolog/session/domain/repository/SessionMemberRepositoryTest.java
Labels: BE, 로드맵

#1504 refactor: Meta Og 글쓰기 버튼 로그인 시에만 활성화 되도록 변경
  backend/src/main/resources/application.yml
  frontend/src/pages/ArticleListPage/index.tsx
Labels: FE, 아티클

#1506 refactor: 아티클 생성시 CREW 권한 확인 로직 추가
  backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
  backend/src/main/java/wooteco/prolog/common/exception/BadRequestCode.java
  backend/src/test/java/wooteco/prolog/article/application/ArticleServiceTest.java
Labels: BE, 아티클

#1507 [FEAT] 아티클 작성시 크루 권한 확인
  backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
  backend/src/main/java/wooteco/prolog/common/exception/BadRequestCode.java
  backend/src/test/java/wooteco/prolog/article/application/ArticleServiceTest.java
  frontend/src/pages/ArticleListPage/index.tsx
Labels: BE, 아티클
