Repository woowacourse/prolog, pull requests merged in 2023-10, with the labels that each got.

#1554 Roadmap endpoint 에 대한 문서화 추가
  backend/src/documentation/adoc/curriculum.adoc
  backend/src/documentation/adoc/essayAnswer.adoc
  backend/src/documentation/adoc/index.adoc
  backend/src/documentation/adoc/keyword.adoc
  backend/src/documentation/adoc/quiz.adoc
  backend/src/documentation/adoc/recommend.adoc
  backend/src/documentation/adoc/roadmap.adoc
  backend/src/documentation/java/wooteco/prolog/NewDocumentation.java
  backend/src/documentation/java/wooteco/prolog/docu/CurriculumDocumentation.java
  backend/src/documentation/java/wooteco/prolog/docu/EssayAnswerDocumentaion.java
  backend/src/documentation/java/wooteco/prolog/docu/KeywordDocumentation.java
  backend/src/documentation/java/wooteco/prolog/docu/NewSessionDocumentation.java
  backend/src/documentation/java/wooteco/prolog/docu/QuizDocumentation.java
  backend/src/documentation/java/wooteco/prolog/docu/RecommendDocument.java
  backend/src/documentation/java/wooteco/prolog/docu/RoadmapDocument.java
  backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
  backend/src/main/resources/static/index.html
Labels: BE, 로드맵

#1564 Refactor: UNVALIDATED 에서 GUEST 로 권한을 변경하고 가입시 기존 권한을 CREW 에서 GUEST 로 변경한다.
  backend/src/acceptanceTest/java/wooteco/prolog/steps/LoginStepDefinitions.java
  backend/src/acceptanceTest/resources/wooteco/prolog/article.feature
  backend/src/acceptanceTest/resources/wooteco/prolog/badges.feature
  backend/src/acceptanceTest/resources/wooteco/prolog/comment.feature
  backend/src/acceptanceTest/resources/wooteco/prolog/curriculum.feature
  backend/src/acceptanceTest/resources/wooteco/prolog/essayanswer.feature
  backend/src/acceptanceTest/resources/wooteco/prolog/filter.feature
  backend/src/acceptanceTest/resources/wooteco/prolog/levellogs.feature
  backend/src/acceptanceTest/resources/wooteco/prolog/member.feature
  backend/src/acceptanceTest/resources/wooteco/prolog/mission.feature
  backend/src/acceptanceTest/resources/wooteco/prolog/profile.feature
  backend/src/acceptanceTest/resources/wooteco/prolog/studylog-create.feature
  backend/src/acceptanceTest/resources/wooteco/prolog/studylog-popular.feature
  backend/src/acceptanceTest/resources/wooteco/prolog/studylog.feature
  backend/src/acceptanceTest/resources/wooteco/prolog/studylogOverview.feature
  backend/src/acceptanceTest/resources/wooteco/prolog/tag.feature
  backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
  backend/src/main/java/wooteco/prolog/login/application/dto/GithubProfileResponse.java
  backend/src/main/java/wooteco/prolog/member/application/MemberService.java
  backend/src/main/java/wooteco/prolog/member/application/dto/RoleUpdateRequest.java
  backend/src/main/java/wooteco/prolog/member/domain/Member.java
  backend/src/main/java/wooteco/prolog/member/domain/Role.java
  backend/src/main/java/wooteco/prolog/member/ui/MemberController.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/wooteco/prolog/article/application/ArticleServiceTest.java
  backend/src/test/java/wooteco/prolog/member/application/MemberServiceTest.java
Labels: BE

#1567 Feature/#1566 비크루 권한 처리 및 조회수 API 추가
  frontend/src/apis/articles.ts
  frontend/src/components/Article/Article.tsx
  frontend/src/contexts/UserProvider.js
  frontend/src/hooks/queries/article.ts
  frontend/src/mocks/handlers/articles.ts
  frontend/src/pages/ArticleListPage/index.tsx
Labels: FE, 아티클

#1572 Refactor/#1571 isBookmarked 변경
  frontend/src/components/Article/Article.tsx
  frontend/src/mocks/db/articles-android.json
  frontend/src/mocks/db/articles-backend.json
  frontend/src/mocks/db/articles-frontend.json
  frontend/src/mocks/db/articles.json
  frontend/src/mocks/handlers/articles.ts
  frontend/src/models/Article.ts
Labels: FE, 아티클

#1562 refactor : 엔드포인트 통일
  backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
  backend/src/main/java/wooteco/prolog/roadmap/ui/EssayAnswerController.java
  backend/src/main/java/wooteco/prolog/roadmap/ui/QuizController.java
Labels: BE, 로드맵

#1574 fix: 체크된 상태 초기값 변경
  frontend/src/components/Article/Article.tsx
Labels: FE, 아티클

#1576 Refactor/#1575 아티클 글쓰기 role 변경
  frontend/src/pages/ArticleListPage/index.tsx
Labels: FE, 아티클

#1578 Fix/#1577 좋아요, 북마크 버튼 클릭 시 아티클 조회수 요청을 보내지 않도록 한다
  frontend/src/components/Article/Article.tsx
Labels: FE, 아티클

#1581 Refactor/#1579 모바일 버전일 때 아티클 글쓰기 버튼 디자인을 변경한다
  frontend/src/pages/ArticleListPage/index.tsx
Labels: FE, 아티클

#1584 Feature/#1524 로드맵 디자인 전면 개편 (Part 2)
  frontend/src/apis/essayanswers.ts
  frontend/src/apis/index.ts
  frontend/src/apis/keywords.ts
  frontend/src/components/CurriculumList/CurriculumList.styles.ts
  frontend/src/components/CurriculumList/CurriculumList.tsx
  frontend/src/mocks/fixtures/quizzes.ts
  frontend/src/mocks/fixtures/roadmap.ts
  frontend/src/mocks/handlers/roadmap.ts
  frontend/src/pages/RoadmapPage/colors.ts
  frontend/src/pages/RoadmapPage/components/ImportanceLegend/ImportanceLegend.styles.ts
  frontend/src/pages/RoadmapPage/components/ImportanceLegend/ImportanceLegend.tsx
  frontend/src/pages/RoadmapPage/components/QuizProgress/QuizProgress.styles.ts
  frontend/src/pages/RoadmapPage/components/QuizProgress/QuizProgress.tsx
  frontend/src/pages/RoadmapPage/components/Roadmap/SubKeyword.tsx
  frontend/src/pages/RoadmapPage/index.tsx
  frontend/src/pages/RoadmapPage/styles.tsx
Labels: FE, 로드맵

#1585 hotfix: 충돌 해결
  frontend/src/pages/ArticleListPage/index.tsx
Labels: bug, FE, 아티클

#1586 fix: 충돌 해결
  frontend/src/pages/ArticleListPage/index.tsx
Labels: bug, FE, 아티클

#1590 Refactor/#1588 navbar&학습로그 권한 있는 사용자만 글쓰기 버튼 활성화
  frontend/src/components/NavBar/NavBar.tsx
  frontend/src/pages/StudylogListPage/index.tsx
Labels: FE, 아티클

#1595 게스트 회원은 로드맵 답변을 쓸 수 없다
  frontend/src/components/KeywordDetailSideSheet/KeywordDetailSideSheet.tsx
  frontend/src/pages/RoadmapPage/index.tsx
  frontend/src/pages/RoadmapPage/styles.tsx
Labels: FE, 로드맵

#1596 게스트 회원은 로드맵 답변을 쓸 수 없다
  frontend/src/components/KeywordDetailSideSheet/KeywordDetailSideSheet.tsx
  frontend/src/pages/RoadmapPage/index.tsx
  frontend/src/pages/RoadmapPage/styles.tsx
Labels: FE, 로드맵

#1593 Hotfix 좋아요, 북마크 비로그인시 api 비활성화
  frontend/src/components/Article/Article.tsx
Labels: FE, 아티클

#1601 fix: 아이콘 Dom 구조 변경으로 인한 드롭다운 표시 에러 수정
  frontend/src/components/DropdownMenu/DropdownMenu.styles.ts
Labels: bug, FE, 아티클

#1604 Safari에서 로드맵 퀴즈 progress가 표시되지 않는 오류를 수정
  frontend/src/pages/RoadmapPage/components/Roadmap/SubKeyword.tsx
Labels: FE, 로드맵

#1605 Member, GroupMember, MemberGroup 엔티티 재설계
  backend/src/acceptanceTest/java/wooteco/prolog/steps/GroupMemberStepDefinitions.java
  backend/src/documentation/java/wooteco/prolog/docu/StudylogDocumentation.java
  backend/src/main/java/wooteco/prolog/article/application/ArticleService.java
  backend/src/main/java/wooteco/prolog/article/domain/ArticleFilterType.java
  backend/src/main/java/wooteco/prolog/article/domain/repository/ArticleRepository.java
  backend/src/main/java/wooteco/prolog/common/exception/BadRequestCode.java
  backend/src/main/java/wooteco/prolog/member/application/DepartmentMemberService.java
  backend/src/main/java/wooteco/prolog/member/application/GroupMemberService.java
  backend/src/main/java/wooteco/prolog/member/domain/Department.java
  backend/src/main/java/wooteco/prolog/member/domain/DepartmentMember.java
  backend/src/main/java/wooteco/prolog/member/domain/Departments.java
  backend/src/main/java/wooteco/prolog/member/domain/MemberGroup.java
  backend/src/main/java/wooteco/prolog/member/domain/MemberGroupType.java
  backend/src/main/java/wooteco/prolog/member/domain/MemberGroups.java
  backend/src/main/java/wooteco/prolog/member/domain/Part.java
  backend/src/main/java/wooteco/prolog/member/domain/Term.java
  backend/src/main/java/wooteco/prolog/member/domain/repository/DepartmentMemberRepository.java
  backend/src/main/java/wooteco/prolog/member/domain/repository/DepartmentRepository.java
  backend/src/main/java/wooteco/prolog/member/domain/repository/GroupMemberRepository.java
  backend/src/main/java/wooteco/prolog/member/domain/repository/MemberGroupRepository.java
  backend/src/main/java/wooteco/prolog/session/application/SessionMemberService.java
  backend/src/main/java/wooteco/prolog/studylog/application/PopularStudylogService.java
  backend/src/main/resources/db/migration/prod/V9__alter_table_group_and_member.sql
  backend/src/test/java/wooteco/prolog/member/application/DepartmentMemberServiceTest.java
  backend/src/test/java/wooteco/prolog/member/application/GroupMemberServiceTest.java
  backend/src/test/java/wooteco/prolog/member/domain/DepartmentTest.java
  backend/src/test/java/wooteco/prolog/member/domain/MemberGroupTest.java
  backend/src/test/java/wooteco/prolog/member/domain/MemberGroupTypeTest.java
  backend/src/test/java/wooteco/prolog/member/domain/repository/DepartmentMemberRepositoryTest.java
  backend/src/test/java/wooteco/prolog/member/domain/repository/GroupMemberRepositoryTest.java
  backend/src/test/java/wooteco/prolog/session/application/SessionMemberServiceTest.java
  backend/src/test/java/wooteco/prolog/studylog/application/PopularStudylogServiceTest.java
Labels: BE, 고도화

#1608 Safari에서 로드맵 퀴즈 progress가 표시되지 않는 오류를 수정
  frontend/src/pages/RoadmapPage/components/Roadmap/SubKeyword.tsx
Labels: FE, 로드맵

#1611 refactor: ES dateTime 타입 및 쿼리 필터 수정
  backend/src/main/java/wooteco/prolog/studylog/domain/StudylogDocument.java
  backend/src/main/java/wooteco/prolog/studylog/domain/StudylogDocumentQueryBuilder.java
Labels: bug, BE
