Repository woowacourse/prolog, pull requests merged in 2023-11, with the labels that each got.

#1613 로드맵 서비스 로직 가독성 개선
  backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
  backend/src/main/java/wooteco/prolog/roadmap/application/RoadMapService.java
  backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordResponse.java
  backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordsResponse.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/Keyword.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/repository/KeywordRepository.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/repository/QuizRepository.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/repository/dto/KeywordIdAndAnsweredQuizCount.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/repository/dto/KeywordIdAndTotalQuizCount.java
  backend/src/test/java/wooteco/prolog/roadmap/application/RecommendedPostServiceTest.java
  backend/src/test/java/wooteco/prolog/roadmap/application/RoadMapServiceTest.java
  backend/src/test/java/wooteco/prolog/roadmap/repository/KeywordRepositoryTest.java
Labels: BE, 로드맵

#1618 로드맵 서비스 로직 리팩토링
  backend/src/main/java/wooteco/prolog/roadmap/application/KeywordService.java
  backend/src/main/java/wooteco/prolog/roadmap/application/RoadMapService.java
  backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordResponse.java
  backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordsResponse.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/Keyword.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/repository/KeywordRepository.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/repository/QuizRepository.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/repository/dto/KeywordIdAndAnsweredQuizCount.java
  backend/src/main/java/wooteco/prolog/roadmap/domain/repository/dto/KeywordIdAndTotalQuizCount.java
  backend/src/test/java/wooteco/prolog/roadmap/application/RecommendedPostServiceTest.java
  backend/src/test/java/wooteco/prolog/roadmap/application/RoadMapServiceTest.java
  backend/src/test/java/wooteco/prolog/roadmap/repository/KeywordRepositoryTest.java
Labels: BE, 로드맵

#1623 응답 DTO의 필드명 변경으로 인한 버그 수정
  backend/src/main/java/wooteco/prolog/roadmap/application/dto/KeywordResponse.java
  backend/src/test/java/wooteco/prolog/roadmap/application/RoadMapServiceTest.java
Labels: bug, BE, 로드맵

#1622 LoginInterceptor 개선
  backend/src/acceptanceTest/java/wooteco/prolog/steps/KeywordRecommendedPostStepDefinitions.java
  backend/src/main/java/wooteco/prolog/login/ui/LoginConfig.java
  backend/src/main/java/wooteco/prolog/login/ui/LoginInterceptor.java
  backend/src/main/java/wooteco/support/autoceptor/AuthenticationDetector.java
  backend/src/main/java/wooteco/support/autoceptor/AutoInterceptorPatternMaker.java
  backend/src/main/java/wooteco/support/autoceptor/MethodPattern.java
  backend/src/main/java/wooteco/support/autoceptor/scanner/MappingAnnotation.java
  backend/src/main/java/wooteco/support/autoceptor/scanner/URIScanner.java
  backend/src/test/java/wooteco/support/autoceptor/MethodPatternTest.java
  backend/src/test/java/wooteco/support/autoceptor/URIScannerTest.java
Labels: BE
