Repository woowacourse/prolog, pull requests merged in 2023-07, with the labels that each got.

#1384 Chore: requests.js 파일 삭제
  frontend/src/service/requests.js
Labels: FE

#1386 Feature/#1356 내가 작성한 로드맵 답변 수정 기능
  backend/src/acceptanceTest/java/wooteco/prolog/AcceptanceContext.java
  backend/src/acceptanceTest/java/wooteco/prolog/steps/EssayAnswerStepDefinitions.java
  backend/src/acceptanceTest/resources/wooteco/prolog/essayanswer.feature
  backend/src/main/java/wooteco/prolog/roadmap/application/dto/EssayAnswerUpdateRequest.java
  backend/src/main/java/wooteco/prolog/roadmap/ui/EssayAnswerController.java
  frontend/src/apis/essayanswers.ts
  frontend/src/hooks/EssayAnswer/useEssayAnswer.ts
  frontend/src/hooks/EssayAnswer/useEssayAnswerList.ts
  frontend/src/hooks/EssayAnswer/useNewEssayAnswer.ts
  frontend/src/hooks/queries/essayanswer.ts
  frontend/src/models/EssayAnswers.ts
  frontend/src/pages/EditEssayAnswerPage/index.tsx
  frontend/src/pages/EssayAnswerPage/Content.js
  frontend/src/pages/EssayAnswerPage/index.tsx
  frontend/src/pages/EssayAnswerPage/styles.tsx
  frontend/src/pages/NewEssayAnswerPage/index.tsx
  frontend/src/pages/index.js
  frontend/src/routes.js
Labels: FE, BE, 로드맵

#1393 Feature/#1385 아티클 조회, 생성 api 로직을 구현한다.
  frontend/src/apis/articles.ts
  frontend/src/hooks/Articles/useArticles.ts
  frontend/src/mocks/db/articles.json
  frontend/src/mocks/handlers/articles.ts
  frontend/src/mocks/handlers/index.ts
Labels: FE, 아티클

#1399 Feature/#1385 아티클 조회, 생성 api 로직을 구현한다.
  frontend/src/apis/articles.ts
  frontend/src/hooks/Articles/useArticles.ts
  frontend/src/mocks/db/articles.json
  frontend/src/mocks/handlers/articles.ts
  frontend/src/mocks/handlers/index.ts
Labels: FE, 아티클

#1400 Feature/#1371 아티클 조회 페이지 구현
  frontend/src/assets/images/article-ex.png
  frontend/src/components/Article/Article.stories.js
  frontend/src/components/Article/Article.style.tsx
  frontend/src/components/Article/Article.tsx
  frontend/src/components/Article/ArticleList.stories.js
  frontend/src/components/Article/ArticleList.style.tsx
  frontend/src/components/Article/ArticleList.tsx
  frontend/src/components/NavBar/NavBar.js
  frontend/src/constants/path.js
  frontend/src/hooks/Articles/useArticles.ts
  frontend/src/models/Article.ts
  frontend/src/pages/ArticleListPage/index.tsx
  frontend/src/pages/index.js
  frontend/src/routes.js
Labels: FE, 아티클

#1404 Refactor/#1403 api axios 사용하는 파일 리팩터링
  frontend/src/apis/comment.ts
  frontend/src/apis/curriculum.ts
  frontend/src/apis/keywords.ts
  frontend/src/apis/levellogs.ts
  frontend/src/apis/studylogs.ts
Labels: FE

#1405 Refactor/#1403 custom axios 리팩터링
  frontend/src/apis/comment.ts
  frontend/src/apis/curriculum.ts
  frontend/src/apis/keywords.ts
  frontend/src/apis/levellogs.ts
  frontend/src/apis/studylogs.ts
Labels: FE

#1408 Feature/#1357 로드맵 답변 수정 기능
  backend/src/main/java/wooteco/prolog/roadmap/application/EssayAnswerService.java
  backend/src/main/java/wooteco/prolog/roadmap/ui/EssayAnswerController.java
  backend/src/test/java/wooteco/prolog/roadmap/application/EssayAnswerServiceTest.java
Labels: BE, 로드맵

#1407 Feature/#1396 키워드 엔티티에 추천 포스트 URL 필드 추가
  backend/src/main/java/wooteco/prolog/roadmap/domain/Keyword.java
  backend/src/main/resources/db/migration/prod/V2__create_table_keyword_reference.sql
Labels: BE, 로드맵

#1406 Feature/1368 아티클 생성 페이지 구현
  frontend/src/apis/articles.ts
  frontend/src/constants/path.js
  frontend/src/hooks/Articles/useArticles.ts
  frontend/src/mocks/handlers/articles.ts
  frontend/src/models/Article.ts
  frontend/src/pages/NewArticlePage/index.tsx
  frontend/src/pages/NewArticlePage/styles.ts
  frontend/src/pages/index.js
  frontend/src/routes.js
Labels: FE

#1410 Feature/1402 로그 모니터링 시스템 구축
  .github/workflows/back-dev.yml
  backend/.ebextensions/02-set-filebeat.config
  backend/.ebextensions/02-set-promtail.config
  backend/deploy-config/promtail-local-config.yaml
Labels: BE, TF

#1420 Refactor/1344 js ts 마이그레이션(index, constant, globalstyles) 및 prettier 재설정
  backend/src/test/java/wooteco/prolog/studylog/application/StudylogSessionServiceTest.java
  frontend/.prettierrc
  frontend/src/App.tsx
  frontend/src/GlobalStyles.js
  frontend/src/GlobalStyles.tsx
  frontend/src/assets/lotties/index.js
  frontend/src/assets/lotties/index.ts
  frontend/src/components/@shared/Icons/CancelIcon.tsx
  frontend/src/components/@shared/SnackBar/SnackBar.js
  frontend/src/components/@shared/SnackBar/SnackBar.styles.ts
  frontend/src/components/@shared/SnackBar/SnackBar.tsx
  frontend/src/components/Button/Button.js
  frontend/src/components/Button/Button.styles.ts
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/PageButton.tsx
  frontend/src/components/Calendar/Calendar.styles.ts
  frontend/src/components/Calendar/Calendar.tsx
  frontend/src/components/DropdownMenu/DropdownMenu.js
  frontend/src/components/DropdownMenu/DropdownMenu.styles.js
  frontend/src/components/DropdownMenu/DropdownMenu.styles.tsx
  frontend/src/components/DropdownMenu/DropdownMenu.tsx
  frontend/src/configs/environment.ts
  frontend/src/constants/errorCode.ts
  frontend/src/constants/index.ts
  frontend/src/constants/input.ts
  frontend/src/constants/localStorage.ts
  frontend/src/constants/message.ts
  frontend/src/constants/path.ts
  frontend/src/constants/profilePageMenu.ts
  frontend/src/constants/reactQueryKey.ts
  frontend/src/constants/requestType.ts
  frontend/src/index.tsx
Labels: FE

#1425 Feature/1353 아티클 crud 기능 구현
  backend/src/acceptanceTest/java/wooteco/prolog/fixtures/ArticleFixture.java
  backend/src/acceptanceTest/java/wooteco/prolog/steps/ArticleStepDefinitions.java
  backend/src/acceptanceTest/resources/wooteco/prolog/article.feature
  backend/src/main/java/wooteco/prolog/article/domain/Article.java
  backend/src/main/java/wooteco/prolog/article/domain/ArticleService.java
  backend/src/main/java/wooteco/prolog/article/domain/Title.java
  backend/src/main/java/wooteco/prolog/article/domain/Url.java
  backend/src/main/java/wooteco/prolog/article/domain/repository/ArticleRepository.java
  backend/src/main/java/wooteco/prolog/article/exception/ArticleNotFoundException.java
  backend/src/main/java/wooteco/prolog/article/exception/ArticleTitleNullOrEmptyException.java
  backend/src/main/java/wooteco/prolog/article/exception/ArticleTitleOverLengthException.java
  backend/src/main/java/wooteco/prolog/article/exception/ArticleUrlNullOrEmptyException.java
  backend/src/main/java/wooteco/prolog/article/exception/ArticleUrlOverLengthException.java
  backend/src/main/java/wooteco/prolog/article/exception/InvalidArticleAuthorException.java
  backend/src/main/java/wooteco/prolog/article/ui/ArticleController.java
  backend/src/main/java/wooteco/prolog/article/ui/ArticleRequest.java
  backend/src/main/java/wooteco/prolog/article/ui/ArticleResponse.java
  backend/src/main/resources/db/migration/prod/V3__create_initial_scheme_squashed.sql
  backend/src/test/java/wooteco/prolog/article/application/ArticleServiceTest.java
  backend/src/test/java/wooteco/prolog/article/domain/ArticleTest.java
  backend/src/test/java/wooteco/prolog/article/domain/TitleTest.java
  backend/src/test/java/wooteco/prolog/article/domain/UrlTest.java
Labels: BE

#1401 Feature/#1371 아티클 조회 페이지 구현
  frontend/src/assets/images/article-ex.png
  frontend/src/components/Article/Article.stories.js
  frontend/src/components/Article/Article.style.tsx
  frontend/src/components/Article/Article.tsx
  frontend/src/components/Article/ArticleList.stories.js
  frontend/src/components/Article/ArticleList.style.tsx
  frontend/src/components/Article/ArticleList.tsx
  frontend/src/components/NavBar/NavBar.js
  frontend/src/constants/path.js
  frontend/src/hooks/Articles/useArticles.ts
  frontend/src/models/Article.ts
  frontend/src/pages/ArticleListPage/index.tsx
  frontend/src/pages/index.js
  frontend/src/routes.js
Labels: FE, 아티클

#1447 Refactor/1443 자바스크립트를 타입스크립트로 마이그레이션한다
  frontend/src/components/DropdownMenu/DropdownMenu.styles.ts
  frontend/src/components/DropdownMenu/DropdownMenu.tsx
  frontend/src/components/GithubLogin/GithubLogin.tsx
  frontend/src/components/Modal/Modal.styles.ts
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/NavBar/NavBar.styles.ts
  frontend/src/components/NavBar/NavBar.tsx
Labels: FE

#1452 Hotfix/1451 프롤로그 글쓰기 기능 핫픽스
  .github/workflows/front-dev.yml
  frontend/src/apis/comment.ts
  frontend/src/apis/curriculum.ts
  frontend/src/apis/keywords.ts
  frontend/src/apis/levellogs.ts
  frontend/src/apis/studylogs.ts
Labels: bug, FE

#1453 Hotfix/1451 프롤로그 글쓰기 기능 핫픽스
  .github/workflows/front-dev.yml
  frontend/src/apis/comment.ts
  frontend/src/apis/curriculum.ts
  frontend/src/apis/keywords.ts
  frontend/src/apis/levellogs.ts
  frontend/src/apis/studylogs.ts
Labels: bug, FE

#1456 feature/1454-아티클_반환_날짜_형식_수정
  backend/src/main/java/wooteco/prolog/article/ui/ArticleResponse.java
Labels: BE, 아티클

#1457 [hotfix] article 테이블 생성 sql 이름 변경
  backend/src/main/resources/db/migration/prod/V3__create_table_article.sql.sql
Labels: BE

#1462 remove: 불필요 sql 삭제
  backend/src/main/resources/db/migration/prod/V3__create_table_article.sql.sql
Labels: BE

#1466 Refactor/#1465 아티클 네비게이션 탭 활성화 및 링크 이동기능 추가
  frontend/src/components/Article/Article.style.tsx
  frontend/src/components/Article/Article.tsx
  frontend/src/components/NavBar/NavBar.tsx
Labels: FE, 아티클

#1467 Refactor/#1465 아티클 네비게이션 및 링크 이동 기능
  frontend/src/components/Article/Article.style.tsx
  frontend/src/components/Article/Article.tsx
  frontend/src/components/NavBar/NavBar.tsx
Labels: FE, 아티클

#1468 Feature/1402 로그 모니터링 시스템 구축
  backend/.ebextensions/02-set-filebeat.config
Labels: BE, TF
