Repository woowacourse/prolog, pull requests merged in 2023-05, with the labels that each got.

#1247 Refactor/#1242 메인화면 배너 깨짐과 글쓰기 시 헤더의 cursor pointer가 안 되는 문제 해결
  frontend/src/GlobalStyles.js
  frontend/src/components/Banner/Banner.styles.ts
  frontend/src/components/Banner/BannerList.styles.ts
  frontend/src/components/NavBar/NavBar.js
Labels: FE

#1258 Feature/#1236 로드맵 상위 키워드 버튼과 스크롤 바 디자인 개선
  frontend/src/GlobalStyles.js
  frontend/src/components/TopKeywordList/TopKeywordList.tsx
Labels: FE

#1262 Refactor/#1239 학습로그 및 로드맵에 margin css 개선
  frontend/src/components/Items/PopularStudylogItem.tsx
  frontend/src/pages/MainPage/RecentStudylogList.tsx
  frontend/src/pages/RoadmapPage/index.tsx
Labels: FE

#1278 build: node 버전 명시 및 의존성 최신버전 사용 방지
  .github/workflows/front-dev.yml
  .github/workflows/front-prod.yml
Labels: bug, FE

#1241 Refactor/#1238 메인 섹션 타이틀 반응형 css 개선
  frontend/src/components/Items/PopularStudylogItem.tsx
  frontend/src/pages/MainPage/PopularStudyLogList.tsx
  frontend/src/styles/reset.styles.ts
Labels: FE

#1282 Refactor/1242 메인화면 배너 깨짐과 글쓰기 시 헤더의 cursor pointer가 안 되는 문제 해결
  frontend/src/GlobalStyles.js
  frontend/src/components/Banner/Banner.styles.ts
  frontend/src/components/Banner/BannerList.styles.ts
  frontend/src/components/NavBar/NavBar.js
Labels: FE

#1283 Refactor/1270 헤어 콘텐츠 깨짐 현상 수정 및 모바일 버전 로고 변경
  frontend/src/components/NavBar/NavBar.js
  frontend/src/constants/screenSize.js
Labels: FE

#1318 Feature/#1280 홍실, 아마란스 테스트 작성
  backend/src/test/java/wooteco/prolog/studylog/application/StudylogSessionServiceTest.java
  backend/src/test/java/wooteco/prolog/studylog/application/StudylogTagServiceTest.java
  backend/src/test/java/wooteco/prolog/studylog/application/TagServiceTest.java
  backend/src/test/java/wooteco/prolog/studylog/application/ViewedStudyLogCookieGeneratorTest.java
Labels: BE

#1319 Feature/1309 홍실 아마란스 테스트 작성
  backend/src/test/java/wooteco/prolog/member/application/GroupMemberServiceTest.java
  backend/src/test/java/wooteco/prolog/member/application/MemberTagServiceTest.java
  backend/src/test/java/wooteco/prolog/studylog/application/StudylogSessionServiceTest.java
Labels: BE

#1320 Feature/#1280 홍실, 아마란스 테스트 작성
  backend/src/test/java/wooteco/prolog/studylog/application/StudylogSessionServiceTest.java
  backend/src/test/java/wooteco/prolog/studylog/application/StudylogTagServiceTest.java
  backend/src/test/java/wooteco/prolog/studylog/application/TagServiceTest.java
  backend/src/test/java/wooteco/prolog/studylog/application/ViewedStudyLogCookieGeneratorTest.java
Labels: BE

#1323 Refactor/#1315 로드맵의 스타일을 수정한다.
  frontend/src/components/@shared/SideSheet/SideSheet.style.ts
  frontend/src/pages/RoadmapPage/styles.tsx
Labels: FE

#1299 refactor/#1269 반응형 디자인 깨짐 현상 수정
  frontend/src/components/FilterList/FilterList.js
  frontend/src/components/FilterList/FilterList.styles.js
  frontend/src/components/ProfileChip/ProfilChip.styles.ts
  frontend/src/pages/StudylogListPage/index.tsx
Labels: FE
